
name: Style Guide Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check_style_guide:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Call Style Guide Checker API
        run: |
          response=$(curl -X POST https://torii-ai-git-staging-torii-studio.vercel.app/api/check-style           -H "Content-Type: application/json"           -d '{
            "repository": "${{ github.repository }}",
            "prNumber": "${{ github.event.pull_request.number }}",
            "clientId": "${{ secrets.TORII_STYLE_CLIENT_ID }}"
          }')
          echo "Response: $response"
          # Parse success field from JSON and check if it's false
          success=$(echo "$response" | jq -r '.success')
          if [ "$success" != "true" ]; then
            echo "Style guide issues found. Failing the check."
            exit 1
          else
            echo "No issues found. Success."
          fi
        env:
          TORII_STYLE_CLIENT_ID: ${{ secrets.TORII_STYLE_CLIENT_ID }}
